package com.kolesnikovprod.ksetaorch.ui.main.launch.common

internal val BootStatusPool = listOf(
    BootStatus.UpToDate,
    BootStatus.UpToDate,
    BootStatus.UpToDate,
    BootStatus.UpToDate,
    BootStatus.Warning,
    BootStatus.Warning,
    BootStatus.Severe,
    BootStatus.Refusal,
    BootStatus.Error,
)

internal val KsenaxBootLines = listOf(
    "> Task :app:checkKotlinGradlePluginConfigurationErrors",
    "> Task :ksenax:igniteKernel",
    "[init] waking local orchestration kernel",
    "[cooling] checking thermal corridor",
    "[battery] handshake with power rail",
    "[connectors] binding screen, touch and haptics",
    "[device] reading density, cutouts and safe zones",
    "[compose] preparing dark launch surface",
    "[voice] microphone route sealed",
    "[privacy] LOCAL memory perimeter online",
    "[agent] loading action grammar",
    "[agent] remote dependency refused by design",
    "[agent] falling back to LOCAL model bus",
    "[security] cloud telemetry blocked",
    "[security] desired error acknowledged",
    "[gradle] resolving tiny pixel fonts",
    "[assets] warming star field atlas",
    "[assets] sunset layer attached",
    "[ui] top bar sockets connected",
    "[ui] bottom bar glow calibrated",
    "[ui] side panel gesture armed",
    "[speech] Gemma STT interface ready",
    "[speech] Vosk experimental slot detected",
    "[math] approximating feeling with finite states",
    "[kotlin] null safety enabled",
    "[java] patience adapter installed",
    "[battery] neon budget accepted",
    "[shader] cyan pulse injected",
    "[shader] blue edge glow stabilized",
    "[runtime] phone shell imprint started",
    "[runtime] connector heartbeat stable",
    "> Task :app:compileDebugKotlin",
    "> Task :app:mergeDebugResources",
    "[compose] preparing main screen handoff",
    "[ksenax] LOCAL control surface ready",
)

internal val RuntimeBootLines = listOf(
    "Initializing Android Runtime...",
    "Loading AI Core...",
    "Bootstrapping Local Agent...",
    "Verifying Android SDK Compatibility...",
    "Checking ABI Compatibility...",
    "Detecting CPU Instruction Set...",
    "Verifying ARM64 Optimizations...",
    "Initializing Neural Runtime...",
    "Loading Language Model...",
    "Reading GGUF Metadata...",
    "Validating Model Header...",
    "Checking Tensor Integrity...",
    "Loading Vocabulary...",
    "Loading Tokenizer...",
    "Loading Merge Rules...",
    "Compiling Prompt Pipeline...",
    "Preparing Context Window...",
    "Allocating KV Cache...",
    "Mapping Model Weights...",
    "Verifying Quantization Format...",
    "Checking Q4_K_M Compatibility...",
    "Checking Q5_K_M Compatibility...",
    "Checking Q6_K Compatibility...",
    "Loading Embedding Matrix...",
    "Initializing Attention Layers...",
    "Initializing Feed Forward Network...",
    "Compiling Inference Graph...",
    "Preparing Sampling Engine...",
    "Loading System Prompt...",
    "Loading Tool Registry...",
    "Loading Agent Modules...",
    "Registering Kotlin Functions...",
    "Generating JSON Tool Schemas...",
    "Building Function Registry...",
    "Checking Reflection Metadata...",
    "Preparing Tool Dispatcher...",
    "Preparing Intent Classifier...",
    "Loading Context Memory...",
    "Restoring Conversation State...",
    "Optimizing Prompt Cache...",
    "Synchronizing Memory Buffers...",
    "Preparing Response Decoder...",
    "Initializing Streaming Engine...",
    "Initializing Voice Pipeline...",
    "Preparing Audio Output...",
    "Loading Wake Word Detector...",
    "Initializing Camera Pipeline...",
    "Preparing Vision Encoder...",
    "Loading OCR Engine...",
    "Loading Image Processor...",
    "Preparing File Index...",
    "Scanning Documents...",
    "Scanning Media Library...",
    "Loading Obsidian Integration...",
    "Building Markdown Parser...",
    "Initializing Semantic Search...",
    "Loading Vector Index...",
    "Preparing Embedding Database...",
    "Checking Storage Permissions...",
    "Verifying Notification Access...",
    "Checking Alarm Permissions...",
    "Checking Accessibility Service...",
    "Checking Overlay Permission...",
    "Initializing Automation Engine...",
    "Compiling Action Graph...",
    "Resolving Dependency Tree...",
    "Checking Execution Pipeline...",
    "Validating Action Parameters...",
    "Preparing Secure Sandbox...",
    "Enabling Background Services...",
    "Synchronizing Agent State...",
    "Loading Runtime Extensions...",
    "Preparing Execution Queue...",
    "Compiling Prompt Templates...",
    "Optimizing Context Compression...",
    "Applying Memory Heuristics...",
    "Initializing Multi-Agent Router...",
    "Loading Planner Module...",
    "Loading Executor Module...",
    "Loading Scheduler...",
    "Building Execution DAG...",
    "Resolving Task Graph...",
    "Analyzing User Intent...",
    "Preparing Tool Selection...",
    "Evaluating Execution Strategy...",
    "Checking Safety Policies...",
    "Preparing Recovery Mechanism...",
    "Loading Error Recovery...",
    "Applying Runtime Optimizations...",
    "Optimizing Token Throughput...",
    "Estimating Inference Latency...",
    "Measuring GPU Availability...",
    "GPU Acceleration Enabled",
    "CPU Backend Selected",
    "NNAPI Backend Available",
    "Loading Vulkan Backend...",
    "Preparing OpenCL Backend...",
    "Initializing Metal Backend...",
    "Checking Hardware Acceleration...",
    "Applying Low-Latency Mode...",
    "Reducing Memory Fragmentation...",
    "Optimizing Thread Scheduler...",
    "Creating Worker Threads...",
    "Starting Background Executors...",
    "Initializing Coroutine Dispatcher...",
    "Preparing Kotlin Runtime...",
    "Loading JNI Bindings...",
    "Connecting Native Engine...",
    "Initializing IPC Channels...",
    "Synchronizing Agent Components...",
    "Finalizing Runtime...",
    "Running Self Diagnostics...",
    "Performing Integrity Check...",
    "System Ready.",
    "Agent Online.",
    "Inference Engine Ready.",
    "Awaiting User Input...",
)

internal val FailureTailBootLines = listOf(
    BootLine("Initializing Runtime Environment...", BootStatus.UpToDate),
    BootLine("Loading Android AI Framework...", BootStatus.UpToDate),
    BootLine("Verifying Model Integrity... OK", BootStatus.UpToDate),
    BootLine("Compiling Execution Pipeline...", BootStatus.UpToDate),
    BootLine("Synchronizing Neural Context...", BootStatus.Warning),
    BootLine("Loading Tool Registry...", BootStatus.UpToDate),
    BootLine("Initializing Agent Memory...", BootStatus.Warning),
    BootLine("Resolving Dependency Graph...", BootStatus.UpToDate),
    BootLine("Preparing Inference Engine...", BootStatus.UpToDate),
    BootLine("Applying Runtime Optimizations...", BootStatus.Warning),
    BootLine("Comp!ling Neur@l Cont3xt...", BootStatus.Severe),
    BootLine("Lo@ding Ag#nt M3mory...", BootStatus.Severe),
    BootLine("Sy#chroniz!ng M0del W€ights...", BootStatus.Error),
    BootLine("Val!dating Tenso® Mapp!ng...", BootStatus.Error),
    BootLine("ERR0R >> C0NT€XT M@PP!NG F41L€D ##@!%₿▓▒░█", BootStatus.Error),
    BootLine("SYS_#RUNTIME::0x7F2A @@@ NULL_REF£RENCE !!! ##", BootStatus.Severe),
    BootLine("NΞUR∆L MØDULΞ ⧖ LØST §YNC █▓▒░ #0xDEADBEEF", BootStatus.Refusal),
    BootLine("FATAL >>> █▓▒░@@@###₿₿₿ΞΞΞ∆∆∆ SYSTEM CØRRUPTED", BootStatus.Severe),
    BootLine(BOOT_FINAL_FAILURE_MESSAGE, BootStatus.Error),
)
