package com.kolesnikovprod.ksetaorch.communication.tools.builtin.notes

import com.kolesnikovprod.ksetaorch.communication.tools.contracts.*
import com.kolesnikovprod.ksetaorch.communication.work.actions.*
import com.kolesnikovprod.ksetaorch.communication.work.oneshot.KsenaxOneShotToolProtocol
import com.kolesnikovprod.ksetaorch.communication.work.oneshot.MissingActionArgument
import com.kolesnikovprod.ksetaorch.communication.work.planning.KsenaxWorkPlanStep
import java.time.ZonedDateTime
import kotlinx.serialization.json.*

/**
 * Передаёт проверенный текст G4 исполнителю, минуя короткий FG-запрос.
 * @author Stephan Kolesnikov
 * @since 0.4
 */
class ObsidianNoteOneShotToolModule(override val executor: KsenaxToolExecutor) : KsenaxOneShotActionKit {
    override val id = "system.obsidian.notes.oneshot"
    override val namespace = "system"
    override val actionSpecs = listOf(
        KsenaxWorkActionSpec(ObsidianNoteOneShot.Write.codeName, "Creates or appends a Markdown note.",
            """{"title":"short note title","markdown_body":"complete Markdown body generated by G4"}"""),
        KsenaxWorkActionSpec(ObsidianNoteOneShot.AppendAnalysis.codeName, "Appends G4-generated analysis to a Markdown note.",
            """{"title":"same note title","analysis_markdown":"analysis generated by G4"}"""),
    )
    override val protocol: KsenaxOneShotToolProtocol = ObsidianNoteOneShotProtocol
    override val exposePlannerInputToFunctionGemma = false

    override fun resolveExecutableCall(userMessage: String, step: KsenaxWorkPlanStep, compiledCall: KsenaxToolCall): KsenaxToolCall {
        val input = step.plannerInputJson?.let { Json.parseToJsonElement(it) as? JsonObject }
            ?: throw MissingActionArgument("содержимое заметки от планировщика")
        val plannedTitle = input.stringByNames("title", "tilte", "note_title", "noteTitle", "name")
        val writing = compiledCall.name == ObsidianNoteOneShot.Write.codeName
        val bodyKey = if (writing) "markdown_body" else "analysis_markdown"
        val body = if (writing) input.stringByNames("markdown_body", "markdownBody", "body", "content", "text", "note")
            else input.stringByNames("analysis_markdown", "analysisMarkdown", "markdown_body", "body", "analysis", "content", "text")
        if (body == null) throw MissingActionArgument(bodyKey)
        require(!Regex("^(запиши|создай|напиши)\\s+(заметку|и запиши)", RegexOption.IGNORE_CASE).containsMatchIn(body.trim())) {
            "Планировщик вернул команду вместо содержимого заметки."
        }
        val payload = buildJsonObject {
            // Запись в ежедневную заметку — существующее правило хранения.
            put("title", if (writing) DAILY_NOTE_TITLE else plannedTitle ?: DAILY_NOTE_TITLE)
            put(bodyKey, body)
        }
        return compiledCall.copy(arguments = KsenaxRawToolArgumentsObject(payload.toString()))
    }

    override fun validateExecutableCall(call: KsenaxToolCall, now: ZonedDateTime) {
        val input = Json.parseToJsonElement(call.arguments.JSONtoString()).jsonObject
        val bodyKey = if (call.name == ObsidianNoteOneShot.Write.codeName) "markdown_body" else "analysis_markdown"
        input.stringByNames("title") ?: throw MissingActionArgument("title")
        input.stringByNames(bodyKey) ?: throw MissingActionArgument(bodyKey)
    }

    private fun JsonObject.stringByNames(vararg names: String): String? = names.firstNotNullOfOrNull { name ->
        val value = get(name) ?: return@firstNotNullOfOrNull null
        require(value is JsonPrimitive && value.isString) { "Поле '$name' заметки должно быть строкой." }
        value.content.trim().takeIf(String::isNotBlank)
    }

    private companion object { const val DAILY_NOTE_TITLE = "Ежедневная заметка" }
}
