package com.kolesnikovprod.ksetaorch.communication.tools.builtin.notes

import com.kolesnikovprod.ksetaorch.communication.tools.contracts.KsenaxRawToolArgumentsObject
import com.kolesnikovprod.ksetaorch.communication.tools.contracts.KsenaxToolCall
import com.kolesnikovprod.ksetaorch.communication.tools.contracts.KsenaxToolExecutor
import com.kolesnikovprod.ksetaorch.communication.work.actions.KsenaxOneShotActionKit
import com.kolesnikovprod.ksetaorch.communication.work.actions.KsenaxWorkActionSpec
import com.kolesnikovprod.ksetaorch.communication.work.oneshot.KsenaxOneShotKeywords
import com.kolesnikovprod.ksetaorch.communication.work.oneshot.KsenaxOneShotToolProtocol
import com.kolesnikovprod.ksetaorch.communication.work.planning.KsenaxWorkPlanStep

class ObsidianNoteOneShotToolModule(
    override val executor: KsenaxToolExecutor,
) : KsenaxOneShotActionKit {

    override val id: String = "system.obsidian.notes.oneshot"

    override val namespace: String = "system"

    override val actionSpecs: List<KsenaxWorkActionSpec> =
        listOf(
            KsenaxWorkActionSpec(
                name = ObsidianNoteOneShot.Write.codeName,
                description = "Creates or appends a Markdown note.",
                inputHint = """{"title":"short note title","markdown_body":"complete Markdown body generated by G4"}""",
                examples = listOf("Запиши мысль X -> obsidian_note_write"),
            ),
            KsenaxWorkActionSpec(
                name = ObsidianNoteOneShot.AppendAnalysis.codeName,
                description = "Appends G4-generated analysis to a Markdown note.",
                inputHint = """{"title":"same note title","analysis_markdown":"analysis generated by G4"}""",
                examples = listOf("Запиши мысль X и проанализируй -> obsidian_note_write + obsidian_note_append_analysis"),
            ),
        )

    override val keywords: KsenaxOneShotKeywords = ObsidianNoteOneShotKeywords

    override val protocol: KsenaxOneShotToolProtocol = ObsidianNoteOneShotProtocol

    override val exposePlannerInputToFunctionGemma: Boolean = false

    override fun resolveExecutableCall(
        userMessage: String,
        step: KsenaxWorkPlanStep,
        compiledCall: KsenaxToolCall,
    ): KsenaxToolCall =
        compiledCall.copy(
            arguments = KsenaxRawToolArgumentsObject(
                step.toObsidianArgumentsJson(
                    actionName = compiledCall.name,
                    userMessage = userMessage,
                ),
            )
        )

    private fun KsenaxWorkPlanStep.toObsidianArgumentsJson(
        actionName: String,
        userMessage: String,
    ): String {
        val input = plannerInputJson.orEmpty()

        val title = when (actionName) {
            ObsidianNoteOneShot.Write.codeName -> DAILY_NOTE_TITLE
            else -> input.stringByJsonNames(
                "title",
                "tilte",
                "note_title",
                "noteTitle",
                "name",
            ) ?: DAILY_NOTE_TITLE
        }

        val body = when (actionName) {
            ObsidianNoteOneShot.Write.codeName -> {
                val plannedBody = input.stringByJsonNames(
                    "markdown_body",
                    "markdownBody",
                    "body",
                    "content",
                    "text",
                    "note",
                )
                plannedBody
                    ?.takeUnless { body -> body.looksLikeOnlyCommand() }
                    ?: userMessage.extractNoteContent()
                    ?: plannedBody
                    ?: instruction
            }
            ObsidianNoteOneShot.AppendAnalysis.codeName -> input.stringByJsonNames(
                "analysis_markdown",
                "analysisMarkdown",
                "markdown_body",
                "body",
                "analysis",
                "content",
                "text",
            ) ?: instruction
            else -> error("Unsupported Obsidian one-shot action: $actionName.")
        }

        val bodyKey = when (actionName) {
            ObsidianNoteOneShot.Write.codeName -> "markdown_body"
            ObsidianNoteOneShot.AppendAnalysis.codeName -> "analysis_markdown"
            else -> error("Unsupported Obsidian one-shot action: $actionName.")
        }
        return buildString {
            append('{')
            append("\"title\":")
            append(title.toJsonString())
            append(',')
            append(bodyKey.toJsonString())
            append(':')
            append(body.toJsonString())
            append('}')
        }
    }

    private fun String.stringByJsonNames(vararg names: String): String? =
        names.firstNotNullOfOrNull { name ->
            jsonStringValue(name)
                .trim()
                .takeIf(String::isNotBlank)
                ?.takeUnless { value -> value == "null" }
        }

    private fun String.jsonStringValue(key: String): String {
        val regex = Regex(
            pattern = """"${Regex.escape(key)}"\s*:\s*"((?:\\.|[^"\\])*)"""",
        )
        val match = regex.find(this) ?: return ""
        return match.groupValues[1].decodeJsonString()
    }

    private fun String.decodeJsonString(): String =
        buildString {
            var index = 0
            while (index < this@decodeJsonString.length) {
                val char = this@decodeJsonString[index]
                if (char == '\\' && index + 1 < this@decodeJsonString.length) {
                    when (val escaped = this@decodeJsonString[index + 1]) {
                        '"'  -> append('"')
                        '\\' -> append('\\')
                        '/'  -> append('/')
                        'n'  -> append('\n')
                        'r'  -> append('\r')
                        't'  -> append('\t')
                        'b'  -> append('\b')
                        'f'  -> append('\u000C')
                        else -> append(escaped)
                    }
                    index += 2
                } else {
                    append(char)
                    index += 1
                }
            }
        }

    private fun String.toJsonString(): String =
        buildString {
            append('"')
            this@toJsonString.forEach { symbol ->
                when (symbol) {
                    '\\' -> append("\\\\")
                    '"'  -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(symbol)
                }
            }
            append('"')
        }

    private fun String.looksLikeOnlyCommand(): Boolean {
        val normalized = lowercase()
        val commandMarkers = listOf(
            "запиши заметку",
            "создай заметку",
            "создай и запиши",
            "напиши заметку",
        )
        return length < 120 && commandMarkers.any { marker -> marker in normalized }
    }

    private fun String.extractNoteContent(): String? {
        val normalized = trim()
        val markers = listOf(
            "о том, что",
            "о том что",
            "то, что",
            "то что",
            "мысль",
            "заметку о том,",
            "заметку о том",
            "заметку",
        )
        val marker = markers.firstOrNull { candidate ->
            normalized.contains(candidate, ignoreCase = true)
        } ?: return normalized.takeIf { it.isNotBlank() }
        val extracted = normalized.substringAfter(marker, missingDelimiterValue = normalized)
            .trim(' ', ',', '.', ':', '-', '—')
        return extracted.takeIf { it.isNotBlank() && it.length >= 8 }
    }

    private companion object {
        const val DAILY_NOTE_TITLE = "Ежедневная заметка"
    }
}
